const express=require("express")
const controllers=require("../controller")
const router=express.Router()
const fetchUser=require("../middleware/fetchUser")



router.post("/signup",controllers.signUpController)
router.post("/signin",controllers.signInController)
router.post("/googleSignin",controllers.googleLogin)
router.post("/forgetPassword",controllers.forgetPassword)
router.post("/forgetPassword/changePassword",controllers.changeOldPasswordForgetPassword)
router.get("/getUser",fetchUser,controllers.getUserData)
router.put("/editUser",fetchUser,controllers.editUserData)
router.post("/uploadImg",fetchUser,controllers.uploadImg)
router.put("/changePassword",fetchUser,controllers.changePassword)
router.post("/createProduct",fetchUser,controllers.createProduct)
router.delete("/deleteProduct/:id",fetchUser,controllers.deleteProduct)
router.put("/editProduct",fetchUser,controllers.editProduct)
router.put("/changeProductImg",fetchUser,controllers.changeProductImg)
router.get("/getAllProduct",controllers.getAllProducts)
router.get("/getProduct/:id",controllers.getProduct)
router.put("/addToCart/:id",fetchUser,controllers.addToCart)
router.put("/editCartItem/:id/:no",fetchUser,controllers.editCartItem)
router.get("/getCartItems",fetchUser,controllers.getCartItems)
router.put("/removeFromCart/:id",fetchUser,controllers.removeFromCart)
router.post("/addAddress",fetchUser,controllers.addAdress)
router.get("/getAddress",fetchUser,controllers.getAddress)
router.get("/totalCartPrice",fetchUser,controllers.returnCartTotal)
router.put("/emptyCart",fetchUser,controllers.emptyCart)
router.get("/getOrders",fetchUser,controllers.getOrders)
router.post("/razorpay/orders",fetchUser,controllers.payWithRazorpay)
router.get("/getAllCategories",controllers.getAllCategories)
router.get("/getAllBrands",controllers.getAllBrands)
router.put("/editCategory",fetchUser,controllers.editCategory)
router.put("/editBrand",fetchUser,controllers.editBrands)
router.delete("/deleteCategory/:cate",fetchUser,controllers.deleteCategory)
router.delete("/deleteBrand/:brand",fetchUser,controllers.deleteBrand)
router.get("/getAllOrders",fetchUser,controllers.getAllOrders)
router.put("/changeOrderStatus/:id",fetchUser,controllers.changeOrderStatus)
router.post("/addComment",fetchUser,controllers.addComment)
router.get("/getProductComments/:id",controllers.getProductCmt)
router.get("/isCommentOwner/:id",fetchUser,controllers.isOwnerOfComment)
router.delete("/deleteComment/:id",fetchUser,controllers.deleteComment)
router.put("/editComment/:id",fetchUser,controllers.editComment)
router.put("/addToCompare",fetchUser,controllers.addToCompare)
router.get("/getCompareList",fetchUser,controllers.getCompareList)
router.put("/removeFromCompare",fetchUser,controllers.removeFromCompare)
module.exports=router